#!/usr/bin/env node

const depcheck = require('depcheck')
const execa = require('execa')

main()

async function main () {
  const packageFolder = process.cwd()

  console.log(`running on folder ${packageFolder}`)

  const unused = await depcheck(packageFolder, { skipMissing: true })

  const { devDependencies, dependencies } = unused

  for (const devDep of devDependencies) {
    const { stdout } = await execa('npm', ['uninstall', devDep]);
    console.log(stdout)
  }

  console.log(`removed ${devDependencies.length} dev deps`)

  for (const dep of dependencies) {
    const { stdout } = await execa('npm', ['uninstall', dep]);
    console.log(stdout)
  }

  console.log(`removed ${devDependencies.length} deps`)
}
